spring.application.name=openai-demo
spring.ai.openai.api-key=<open_api_key>
spring.ai.vectorstore.pinecone.api-key=<pinecode api key>
spring.ai.vectorstore.pinecone.index-name=springdemo1
spring.ai.vectorstore.pinecone.namespace=
spring.ai.vectorstore.pinecone.initialize-schema=false

# Set to true only when you want to load job listings into Pinecone
# After first initialization, set this back to false to prevent duplicates
app.initialize-vector-store=true
spring.servlet.multipart.max-file-size=10MB
